version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres_1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
    networks:
      - nest_network

  redis:
    image: redis:alpine
    container_name: nest_redis_1
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redis_data_1:/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest_pgadmin_1
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5051:80'
    volumes:
      - pgadmin_data_1:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nest_network

volumes:
  postgres_data_1:
  redis_data_1:
  pgadmin_data_1:

networks:
  nest_network:
    external: true
