version: '3.8'

services:
  app:
    build: .
    container_name: nest_app_1
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - '8081:8080'
    depends_on:
      - postgres
      - redis
    networks:
      - nest_network

networks:
  nest_network:
    external: true
