version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  redis:
    image: redis:alpine
    container_name: nest_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - nest_network

  # app:
  #   build: .
  #   container_name: nest_app
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - nest_network

volumes:
  postgres_data:
  redis_data:

networks:
  nest_network:
